# Generated by Django 5.1.6 on 2025-02-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_body_post_description_rename_title_post_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritesComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=18)),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posts.favorites')),
            ],
        ),
    ]
