# Generated by Django 5.1.6 on 2025-02-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorites_favoritescomponents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
